
name: 'segment_integration_tests'
version: '1.0'

profile: 'integration_tests'

require-dbt-version: ">=0.15.0"

models:
  segment:
    vars:
      segment_page_views_table: "{{ ref('example_segment_pages') }}"
